---
apiVersion: v1
kind: Service
metadata:
  name: kubtest-dashboard
  namespace: kubtest
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 80
  selector:
    app: kubtest-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubtest-dashboard
  namespace: kubtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubtest-dashboard
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubtest-dashboard
    spec:
      containers:
        - name: petstore-backend
          image: docker.io/kubeshop/kubtest-dashboard:latest
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1


